# -*- coding: utf-8 -*-
"""ocr_pt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQedlr0WbkRiAjzxXBf3RawLXU8kV23U
"""

!pip install pytesseract

from PIL import Image

import pytesseract as pt

def simple_ocr(*imgs):
  for img in imgs:
    text = (pt.image_to_string(Image.open(img)))
    with open("text.txt", 'a') as f:
       print((text), file = f)

simple_ocr('/content/wk_1.png', '/content/wk_2.jpg', '/content/wk_3.png')

"""Źródła: https://forum.pasja-informatyki.pl/506885/zapisywanie-wyniku-funkcji-w-pliku, https://szkoladevnet.pl/tajemnicze-args-i-kwargs/"""